### ISSUE TITLE
Suggestion: Event Bus addresses are an API, and as such it should be versioned.

### ISSUE THREAD

**Issue by InfoSec812** [sherl0cks/explore-ddd-2018-demo#2]
https://github.com/sherl0cks/explore-ddd-2018-demo/blob/5a9a49f14e28ad456c7e80df3ea39b8ea3b8ce3c/producer/src/main/java/io/openinnovationlabs/domain/eventstore/EventStore.java#L27

Example: Change

```
MessageConsumer<JsonObject> appendConsumer = vertx.eventBus().consumer("EventStore-Append");
```

To

```
MessageConsumer<JsonObject> appendConsumer = vertx.eventBus().consumer("v1-EventStore-Append");
```

**Comment by sherl0cks** [comment]
Resolved with recent commits.
